
import { prisma } from '@/lib/prisma';
import { scrapeWebsite } from '@/lib/scraper';
import { NextResponse } from 'next/server';
import RSS from 'rss';

export async function GET(
    request: Request,
    { params }: { params: Promise<{ id: string }> }
) {
    try {
        const { id } = await params;
        const feedConfig = await prisma.feed.findUnique({
            where: { id },
        });

        if (!feedConfig) {
            return NextResponse.json({ error: 'Feed not found' }, { status: 404 });
        }

        const items = await scrapeWebsite({
            url: feedConfig.url,
            itemSelector: feedConfig.itemSelector,
            titleSelector: feedConfig.titleSelector,
            linkSelector: feedConfig.linkSelector,
        });

        const feed = new RSS({
            title: feedConfig.name,
            description: `RSS feed for ${feedConfig.url} generated by RSS Hub`,
            feed_url: `${new URL(request.url).origin}/api/rss/${id}`,
            site_url: feedConfig.url,
            generator: 'RSS Hub',
        });

        items.forEach((item) => {
            feed.item({
                title: item.title,
                url: item.link,
                description: item.content || 'No description available',
                date: new Date(),
            });
        });

        return new NextResponse(feed.xml({ indent: true }), {
            headers: {
                'Content-Type': 'application/xml',
                'Cache-Control': 's-maxage=3600, stale-while-revalidate',
            },
        });
    } catch (error) {
        console.error('RSS Generation Error:', error);
        return NextResponse.json({ error: 'Failed to generate RSS' }, { status: 500 });
    }
}
